import argparse
import csv
import os
import socket
from datetime import datetime
from pathlib import Path

import oracledb


COLUNAS_CSV = [
    "data_hora",
    "timestamp_ms",
    "umidade",
    "ph",
    "n_ok",
    "p_ok",
    "k_ok",
    "chuva_prevista",
    "bomba",
]


DDL_TABELA = """
CREATE TABLE {tabela} (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_hora TIMESTAMP NOT NULL,
  timestamp_ms NUMBER NOT NULL,
  umidade NUMBER(8,2),
  ph NUMBER(8,2),
  n_ok NUMBER(1),
  p_ok NUMBER(1),
  k_ok NUMBER(1),
  chuva_prevista NUMBER(1),
  bomba VARCHAR2(20),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT {constraint_name} UNIQUE (timestamp_ms)
)
"""


MERGE_SQL = """
MERGE INTO {tabela} destino
USING (
  SELECT
    :data_hora AS data_hora,
    :timestamp_ms AS timestamp_ms,
    :umidade AS umidade,
    :ph AS ph,
    :n_ok AS n_ok,
    :p_ok AS p_ok,
    :k_ok AS k_ok,
    :chuva_prevista AS chuva_prevista,
    :bomba AS bomba
  FROM dual
) origem
ON (destino.timestamp_ms = origem.timestamp_ms)
WHEN NOT MATCHED THEN
  INSERT (
    data_hora,
    timestamp_ms,
    umidade,
    ph,
    n_ok,
    p_ok,
    k_ok,
    chuva_prevista,
    bomba
  )
  VALUES (
    origem.data_hora,
    origem.timestamp_ms,
    origem.umidade,
    origem.ph,
    origem.n_ok,
    origem.p_ok,
    origem.k_ok,
    origem.chuva_prevista,
    origem.bomba
  )
"""


def obter_variavel(nome):
    valor = os.environ.get(nome)
    if not valor:
        raise RuntimeError(f"Configure a variavel de ambiente {nome}.")
    return valor


def normalizar_nome_tabela(nome):
    nome = nome.upper()
    if not nome.replace("_", "").isalnum():
        raise ValueError("Nome de tabela invalido. Use apenas letras, numeros e underscore.")
    return nome


def constraint_unica(tabela):
    nome = f"UK_{tabela}_TS"
    return nome[:30]


def conectar():
    usuario = obter_variavel("ORACLE_USER")
    senha = obter_variavel("ORACLE_PASSWORD")
    dsn = obter_variavel("ORACLE_DSN")
    return oracledb.connect(user=usuario, password=senha, dsn=dsn)


def criar_tabela_se_precisar(conexao, tabela):
    cursor = conexao.cursor()
    cursor.execute(
        "SELECT COUNT(*) FROM user_tables WHERE table_name = :nome",
        {"nome": tabela},
    )
    existe = cursor.fetchone()[0] > 0

    if existe:
        return

    cursor.execute(
        DDL_TABELA.format(
            tabela=tabela,
            constraint_name=constraint_unica(tabela),
        )
    )
    conexao.commit()
    print(f"Tabela criada: {tabela}")


def converter_registro(linha):
    return {
        "data_hora": datetime.fromisoformat(linha["data_hora"]),
        "timestamp_ms": int(linha["timestamp_ms"]),
        "umidade": float(linha["umidade"]),
        "ph": float(linha["ph"]),
        "n_ok": int(linha["n_ok"]),
        "p_ok": int(linha["p_ok"]),
        "k_ok": int(linha["k_ok"]),
        "chuva_prevista": int(linha["chuva_prevista"]),
        "bomba": linha["bomba"],
    }


def ler_csv(caminho):
    with Path(caminho).open(newline="", encoding="utf-8") as arquivo:
        leitor = csv.DictReader(arquivo)
        if leitor.fieldnames != COLUNAS_CSV:
            raise RuntimeError(
                "Cabecalho CSV invalido. Esperado: " + ",".join(COLUNAS_CSV)
            )
        return [converter_registro(linha) for linha in leitor]


def importar_csv(caminho_csv, tabela, criar_tabela):
    tabela = normalizar_nome_tabela(tabela)
    registros = ler_csv(caminho_csv)

    if not registros:
        print("Nenhum registro encontrado no CSV.")
        return

    try:
        with conectar() as conexao:
            if criar_tabela:
                criar_tabela_se_precisar(conexao, tabela)

            sql = MERGE_SQL.format(tabela=tabela)
            cursor = conexao.cursor()
            cursor.executemany(sql, registros)
            conexao.commit()
    except socket.gaierror as erro:
        raise RuntimeError(
            "Nao foi possivel resolver o host do Oracle informado em ORACLE_DSN. "
            "Confira se o DSN esta no formato correto, por exemplo "
            "'localhost:1521/XEPDB1' ou 'host:1521/service_name'. "
            f"Erro original: {erro}"
        ) from erro
    except oracledb.Error as erro:
        raise RuntimeError(
            "Falha ao conectar/importar no Oracle. Confira ORACLE_USER, "
            "ORACLE_PASSWORD, ORACLE_DSN, porta, service_name e permissoes da tabela. "
            f"Erro original: {erro}"
        ) from erro

    print(f"Registros processados: {len(registros)}")
    print(f"Tabela Oracle: {tabela}")


def main():
    parser = argparse.ArgumentParser(
        description="Importa dados_sensores.csv para uma tabela Oracle."
    )
    parser.add_argument(
        "--csv",
        default="dados_sensores.csv",
        help="Arquivo CSV de entrada. Padrao: dados_sensores.csv",
    )
    parser.add_argument(
        "--tabela",
        default="DADOS_SENSORES",
        help="Nome da tabela Oracle. Padrao: DADOS_SENSORES",
    )
    parser.add_argument(
        "--sem-criar-tabela",
        action="store_true",
        help="Nao cria a tabela automaticamente.",
    )

    args = parser.parse_args()
    importar_csv(args.csv, args.tabela, criar_tabela=not args.sem_criar_tabela)


if __name__ == "__main__":
    main()
